# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bargain-hunter"
client_id = "b33e93da065728ab025c58bfc6609d5e"
application_url = "https://bargin-hunter2.vercel.app/app"
embedded = true

[access_scopes]
# https://shopify.dev/docs/api/usage/access-scopes
scopes = "read_products,write_discounts,read_customers,write_script_tags,read_orders"

[auth]
redirect_urls = [
  "https://bargin-hunter2.vercel.app/api/auth/callback",
  "https://bargin-hunter2.vercel.app/api/auth/shopify/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE_URL"
include_config_on_deploy = true

[[build.extensions]]
type = "web_pixel"
name = "bargain-hunter-pixel"
metafields = []

[build.extensions.targeting]
default_placement = "ORDER_STATUS"
